language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rainbowlemon' ]; then cd .. && eval "mv $currentfolder generator-rainbowlemon" && cd generator-rainbowlemon; fi

